CREATE TABLE IF NOT EXISTS moves (
	id SERIAL PRIMARY KEY,
	game_id INTEGER REFERENCES games(id) ON DELETE CASCADE,
	player_id INTEGER REFERENCES players(id),
	move_number INTEGER NOT NULL,
	x INTEGER NOT NULL,
	y INTEGER NOT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_moves_game_id ON moves(game_id);
